import Head from 'next/head';

export default function Home() {
  return (
    <div className=''>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='flex flex-col items-center min-h-screen'>
        <h1 className='text-6xl my-4 py-4'>This Is The Main Content Page</h1>
        <p className='text-xl my-4 leading-loose'>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Enim eius
          ducimus architecto. Laboriosam, quibusdam aut at beatae praesentium
          minima reiciendis in cumque blanditiis incidunt dignissimos qui sit
          fugit maxime sed?
        </p>
        <p className='text-xl my-4'>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore
          eligendi ducimus adipisci quos deserunt, natus eveniet ex. Corporis
          eum id dicta reiciendis fugit tempore ducimus, aperiam, aspernatur ab,
          harum illum.
        </p>
      </main>
    </div>
  );
}
